-- MySQL Script generated by MySQL Workbench
-- Sun Oct 19 22:37:50 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nama` VARCHAR(255) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) NULL,
  `jenis_kelamin` ENUM('L', 'P') NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tahun_ajaran`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tahun_ajaran` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nama_tahun` VARCHAR(20) NOT NULL,
  `semester` ENUM("Ganjil", "Genap") NOT NULL DEFAULT 'Ganjil',
  `tanggal_mulai` DATE NULL,
  `tanggal_selesai` DATE NULL,
  `status` ENUM("aktif", "nonaktif") NOT NULL DEFAULT 'aktif',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nama_tahun_UNIQUE` (`nama_tahun` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`kelas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`kelas` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tingkat_kelas` TINYINT NOT NULL,
  `grup_kelas` CHAR(1) NOT NULL,
  `wali_kelas_id` BIGINT UNSIGNED NOT NULL,
  `tahun_ajaran_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_kelas_users1_idx` (`wali_kelas_id` ASC) VISIBLE,
  INDEX `fk_kelas_tahun_ajaran1_idx` (`tahun_ajaran_id` ASC) VISIBLE,
  INDEX `tingkat_kelas_idx` (`tingkat_kelas` ASC) INVISIBLE,
  INDEX `grup_kelas_idx` (`grup_kelas` ASC) INVISIBLE,
  CONSTRAINT `fk_kelas_users1`
    FOREIGN KEY (`wali_kelas_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_kelas_tahun_ajaran1`
    FOREIGN KEY (`tahun_ajaran_id`)
    REFERENCES `mydb`.`tahun_ajaran` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`siswa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`siswa` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nis` VARCHAR(20) NULL,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `kelas_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nis_UNIQUE` (`nis` ASC) VISIBLE,
  INDEX `fk_siswa_users_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_siswa_kelas1_idx` (`kelas_id` ASC) VISIBLE,
  CONSTRAINT `fk_siswa_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_siswa_kelas1`
    FOREIGN KEY (`kelas_id`)
    REFERENCES `mydb`.`kelas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mata_pelajaran`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mata_pelajaran` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nama_mapel` VARCHAR(100) NOT NULL,
  `guru_id` BIGINT NOT NULL,
  `kelas_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_mata_pelajaran_users1_idx` (`guru_id` ASC) VISIBLE,
  INDEX `fk_mata_pelajaran_kelas1_idx` (`kelas_id` ASC) VISIBLE,
  CONSTRAINT `fk_mata_pelajaran_users1`
    FOREIGN KEY (`guru_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mata_pelajaran_kelas1`
    FOREIGN KEY (`kelas_id`)
    REFERENCES `mydb`.`kelas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aktivitas_pembelajaran`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aktivitas_pembelajaran` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `tanggal` DATE NOT NULL,
  `topik` VARCHAR(255) NULL,
  `catatan` TEXT NULL,
  `kelas_id` BIGINT NOT NULL,
  `mata_pelajaran_id` BIGINT NOT NULL,
  `guru_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_aktivitas_pembelajaran_kelas1_idx` (`kelas_id` ASC) VISIBLE,
  INDEX `fk_aktivitas_pembelajaran_mata_pelajaran1_idx` (`mata_pelajaran_id` ASC) VISIBLE,
  INDEX `fk_aktivitas_pembelajaran_users1_idx` (`guru_id` ASC) VISIBLE,
  CONSTRAINT `fk_aktivitas_pembelajaran_kelas1`
    FOREIGN KEY (`kelas_id`)
    REFERENCES `mydb`.`kelas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aktivitas_pembelajaran_mata_pelajaran1`
    FOREIGN KEY (`mata_pelajaran_id`)
    REFERENCES `mydb`.`mata_pelajaran` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aktivitas_pembelajaran_users1`
    FOREIGN KEY (`guru_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`detail_aktivitas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`detail_aktivitas` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `kehadiran` ENUM('hadir', 'izin', 'sakit', 'alpa') NULL DEFAULT 'alpa',
  `nilai` DECIMAL(5,2) NULL,
  `partisipasi` TINYINT NULL,
  `catatan` TEXT NULL,
  `aktivitas_pembelajaran_id` BIGINT UNSIGNED NOT NULL,
  `siswa_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_detail_aktivitas_aktivitas_pembelajaran1_idx` (`aktivitas_pembelajaran_id` ASC) VISIBLE,
  INDEX `fk_detail_aktivitas_siswa1_idx` (`siswa_id` ASC) VISIBLE,
  CONSTRAINT `fk_detail_aktivitas_aktivitas_pembelajaran1`
    FOREIGN KEY (`aktivitas_pembelajaran_id`)
    REFERENCES `mydb`.`aktivitas_pembelajaran` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detail_aktivitas_siswa1`
    FOREIGN KEY (`siswa_id`)
    REFERENCES `mydb`.`siswa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`laporan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`laporan` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rata_kehadiran` FLOAT NULL,
  `rata_nilai` FLOAT NULL,
  `rata_partisipasi` FLOAT NULL,
  `siswa_id` INT NOT NULL,
  `mata_pelajaran_id` INT NOT NULL,
  `tahun_ajaran_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_laporan_siswa1_idx` (`siswa_id` ASC) VISIBLE,
  INDEX `fk_laporan_mata_pelajaran1_idx` (`mata_pelajaran_id` ASC) VISIBLE,
  INDEX `fk_laporan_tahun_ajaran1_idx` (`tahun_ajaran_id` ASC) VISIBLE,
  CONSTRAINT `fk_laporan_siswa1`
    FOREIGN KEY (`siswa_id`)
    REFERENCES `mydb`.`siswa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_laporan_mata_pelajaran1`
    FOREIGN KEY (`mata_pelajaran_id`)
    REFERENCES `mydb`.`mata_pelajaran` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_laporan_tahun_ajaran1`
    FOREIGN KEY (`tahun_ajaran_id`)
    REFERENCES `mydb`.`tahun_ajaran` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
