sonar.projectKey=sippel
sonar.projectName=Sippel
sonar.sources=app,routes,resources
sonar.tests=tests
sonar.php.coverage.reportPaths=coverage.xml
sonar.exclusions=vendor/**,node_modules/**,storage/**,bootstrap/cache/**
